"""
Nginx configuration manager.

Architecture
------------
/etc/nginx/nginx.conf                          ← main config
/etc/nginx/snippets/ssl-params.conf            ← shared TLS settings
/etc/nginx/snippets/cloudflare-realip.conf     ← CF real-IP unwrapping
/etc/nginx/snippets/cloudflare-allow.conf      ← CF IP allowlist + deny all
/etc/nginx/sites-available/<domain>.conf       ← generated per-domain
/etc/nginx/sites-enabled/<domain>.conf         ← symlink → sites-available
/etc/nginx/sites-available/<domain>.http.conf  ← HTTP-only (pre-SSL / ACME)

Traffic flow per customer domain
---------------------------------
  Visitor
    ↓  DNS: customer-domain.com → our server IP (via Cloudflare)
  Cloudflare edge (TLS termination or pass-through)
    ↓  HTTPS to our server IP
  Nginx (port 443)
    · Validates SSL cert for customer-domain.com
    · Unwraps real visitor IP from CF-Connecting-IP header
    · Rejects requests NOT from Cloudflare IPs (cloudflare-allow.conf)
    ↓  proxy_pass → customer's backend_url (stored in DB)
  Customer's origin server
    ↓  Response
  Visitor

Scalability notes
-----------------
- `nginx -s reload` is graceful: workers finish in-flight requests first.
- Always call test_config() before reload() to prevent crashing live traffic.
- For batch domain adds, write all configs then call reload() once.
- With 10k+ domains add to nginx.conf:
    server_names_hash_max_size   65536;
    server_names_hash_bucket_size 128;
"""

import logging
import os
import subprocess
from pathlib import Path
from typing import Tuple

from ..config import settings

logger = logging.getLogger(__name__)


# ── Nginx config templates ────────────────────────────────────────────────────

_HTTP_ONLY_CONF = """\
# HTTP-only vhost for {domain}
# Purpose: serve ACME HTTP-01 challenge BEFORE the SSL cert is issued.
# Once SSL is provisioned this file is deleted and replaced by the full config.
server {{
    listen 80;
    server_name {domain};

    # Required so Cloudflare can reach the ACME challenge endpoint.
    # CF always connects from its own IPs, so no IP restriction here.

    # ACME webroot challenge
    location /.well-known/acme-challenge/ {{
        root {acme_webroot};
        try_files $uri =404;
    }}

    # Redirect all other HTTP to HTTPS immediately
    location / {{
        return 301 https://$host$request_uri;
    }}
}}
"""

# Full HTTPS reverse-proxy config with Cloudflare integration.
# Key design decisions:
#   - `include cloudflare-allow.conf`  → drop non-CF traffic at nginx level
#   - `include cloudflare-realip.conf` → $remote_addr becomes real visitor IP
#   - proxy_set_header passes real visitor IP to the customer's origin
#   - proxy_ssl_server_name on         → SNI for HTTPS backends
#   - proxy_ssl_verify off             → avoids cert issues on private origins
#     (set to `on` + add ca-cert if you need strict backend TLS verification)
_SSL_CONF = """\
# HTTPS reverse-proxy config for {domain}
# Generated by translation-proxy – DO NOT EDIT MANUALLY.
# Changes will be overwritten on next provision-ssl call.

# ── HTTP → HTTPS redirect + ACME challenge ────────────────────────────────────
server {{
    listen 80;
    server_name {domain};

    location /.well-known/acme-challenge/ {{
        root {acme_webroot};
        try_files $uri =404;
    }}

    location / {{
        return 301 https://$host$request_uri;
    }}
}}

# ── HTTPS reverse proxy ───────────────────────────────────────────────────────
server {{
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {domain};

    # ── Cloudflare protection ─────────────────────────────────────────────────
    # Only Cloudflare edge IPs may reach this vhost.
    # Any direct connection from a non-CF IP gets 403 / connection drop.
    include {snippets_dir}/cloudflare-allow.conf;

    # Unwrap real visitor IP from CF-Connecting-IP header.
    # After this, $remote_addr = real visitor IP everywhere in this block.
    include {snippets_dir}/cloudflare-realip.conf;

    # ── TLS ───────────────────────────────────────────────────────────────────
    ssl_certificate     {ssl_cert};
    ssl_certificate_key {ssl_key};
    include             {snippets_dir}/ssl-params.conf;

    # ── Security headers ──────────────────────────────────────────────────────
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    add_header X-Content-Type-Options    "nosniff"    always;
    add_header X-Frame-Options           "SAMEORIGIN" always;
    add_header Referrer-Policy           "strict-origin-when-cross-origin" always;

    # ── Proxy to customer origin ──────────────────────────────────────────────
    location / {{
        proxy_pass         {backend_url};
        proxy_http_version 1.1;

        # WebSocket support
        proxy_set_header   Upgrade     $http_upgrade;
        proxy_set_header   Connection  $connection_upgrade;

        # Tell the origin who the real visitor is (real IP, not CF/our IP)
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $remote_addr;
        proxy_set_header   X-Forwarded-Proto $scheme;

        # Pass Cloudflare-specific visitor info to origin (useful for geo, bot scoring)
        proxy_set_header   CF-Connecting-IP  $http_cf_connecting_ip;
        proxy_set_header   CF-IPCountry      $http_cf_ipcountry;
        proxy_set_header   CF-Ray            $http_cf_ray;
        proxy_set_header   CF-Visitor        $http_cf_visitor;

        # Remove hop-by-hop headers that shouldn't be forwarded
        proxy_hide_header  X-Powered-By;

        # TLS to backend (works for both http:// and https:// backend_urls)
        proxy_ssl_server_name on;
        proxy_ssl_verify      off;   # set to on + add ca bundle for strict verification

        # Timeouts (increase for slow/large responses)
        proxy_connect_timeout  15s;
        proxy_send_timeout     60s;
        proxy_read_timeout     60s;

        # Response buffering (reduces backend connections under load)
        proxy_buffering         on;
        proxy_buffer_size       16k;
        proxy_buffers          16 16k;
        proxy_busy_buffers_size 32k;
        proxy_max_temp_file_size 0;

        # Error handling – show our error page, not the backend's
        proxy_intercept_errors on;
    }}

    # ── Custom error pages ────────────────────────────────────────────────────
    error_page 502 503 504 /50x.html;
    location = /50x.html {{
        root /var/www/html;
        internal;
    }}
}}
"""

_SSL_PARAMS = """\
# Shared TLS configuration – generated by translation-proxy.
ssl_protocols TLSv1.2 TLSv1.3;
ssl_prefer_server_ciphers off;
ssl_dhparam /etc/nginx/dhparam.pem;
ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256;
ssl_session_cache   shared:SSL:10m;
ssl_session_timeout 1d;
ssl_session_tickets off;
ssl_stapling        on;
ssl_stapling_verify on;
resolver 8.8.8.8 1.1.1.1 valid=300s;
resolver_timeout 5s;
"""


# ── Helpers ───────────────────────────────────────────────────────────────────

def _run(cmd: list[str], timeout: int = 30) -> Tuple[int, str, str]:
    result = subprocess.run(
        ["sudo"] + cmd, capture_output=True, text=True, timeout=timeout
    )
    return result.returncode, result.stdout, result.stderr


def _available_path(domain: str, suffix: str = "") -> Path:
    return Path(settings.NGINX_SITES_AVAILABLE) / f"{domain}{suffix}.conf"


def _enabled_path(domain: str, suffix: str = "") -> Path:
    return Path(settings.NGINX_SITES_ENABLED) / f"{domain}{suffix}.conf"


def _enable(domain: str, suffix: str = "") -> None:
    avail = _available_path(domain, suffix)
    enbld = _enabled_path(domain, suffix)
    if not enbld.exists():
        enbld.symlink_to(avail)


def _disable(domain: str, suffix: str = "") -> None:
    enbld = _enabled_path(domain, suffix)
    if enbld.exists() or enbld.is_symlink():
        enbld.unlink()


def _write(path: Path, content: str) -> None:
    """Write file, creating parent dirs as needed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


# ── Public API ────────────────────────────────────────────────────────────────

class NginxManager:
    def __init__(self):
        self._ensure_dirs()
        self._write_ssl_params()
        self._write_error_pages()

    # ── Init ──────────────────────────────────────────────────────────────────

    def _ensure_dirs(self):
        for d in [
            settings.NGINX_SITES_AVAILABLE,
            settings.NGINX_SITES_ENABLED,
            settings.NGINX_SNIPPETS_DIR,
            settings.NGINX_ACME_WEBROOT,
        ]:
            os.makedirs(d, exist_ok=True)

    def _write_ssl_params(self):
        p = Path(settings.NGINX_SNIPPETS_DIR) / "ssl-params.conf"
        if not p.exists():
            _write(p, _SSL_PARAMS)
            logger.info("Written ssl-params.conf")

    def _write_error_pages(self):
        """Write a simple 502/503/504 error page used by all vhosts."""
        html = Path("/var/www/html/50x.html")
        if not html.exists():
            try:
                _write(html, (
                    "<!DOCTYPE html><html><head><title>Service Unavailable</title></head>"
                    "<body><h1>Service temporarily unavailable</h1>"
                    "<p>The origin server is not responding. Please try again shortly.</p>"
                    "</body></html>\n"
                ))
            except Exception:
                pass   # not fatal

    # ── HTTP-only (pre-SSL) ───────────────────────────────────────────────────

    def write_http_only_config(self, domain: str) -> str:
        content = _HTTP_ONLY_CONF.format(
            domain=domain,
            acme_webroot=settings.NGINX_ACME_WEBROOT,
        )
        path = _available_path(domain, ".http")
        _write(path, content)
        _enable(domain, ".http")
        logger.info("HTTP-only config written for %s", domain)
        return str(path)

    def remove_http_only_config(self, domain: str) -> None:
        _disable(domain, ".http")
        p = _available_path(domain, ".http")
        if p.exists():
            p.unlink()

    # ── Full SSL config ───────────────────────────────────────────────────────

    def write_ssl_config(
        self, domain: str, backend_url: str, ssl_cert: str, ssl_key: str
    ) -> str:
        """
        Write the full HTTPS reverse-proxy config for a domain.
        Includes Cloudflare IP allow-list and real-IP unwrapping.
        Returns the config file path.
        """
        content = _SSL_CONF.format(
            domain=domain,
            backend_url=backend_url,
            ssl_cert=ssl_cert,
            ssl_key=ssl_key,
            acme_webroot=settings.NGINX_ACME_WEBROOT,
            snippets_dir=settings.NGINX_SNIPPETS_DIR,
        )
        path = _available_path(domain)
        _write(path, content)
        _enable(domain)
        self.remove_http_only_config(domain)
        logger.info("SSL config written for %s → %s", domain, backend_url)
        return str(path)

    # ── Remove a domain ───────────────────────────────────────────────────────

    def remove_domain_config(self, domain: str) -> None:
        _disable(domain)
        _disable(domain, ".http")
        for p in [_available_path(domain), _available_path(domain, ".http")]:
            if p.exists():
                p.unlink()
        logger.info("Nginx config removed for %s", domain)

    # ── Validate & reload ─────────────────────────────────────────────────────

    def test_config(self) -> Tuple[bool, str]:
        rc, stdout, stderr = _run(["nginx", "-t"])
        ok  = rc == 0
        msg = (stdout + stderr).strip()
        if not ok:
            logger.error("nginx -t FAILED: %s", msg)
        return ok, msg

    def reload(self) -> Tuple[bool, str]:
        """Gracefully reload nginx after validating config."""
        ok, msg = self.test_config()
        if not ok:
            return False, f"Config test failed – reload aborted: {msg}"
        rc, stdout, stderr = _run(["nginx", "-s", "reload"])
        if rc == 0:
            logger.info("nginx reloaded")
            return True, "nginx reloaded"
        err = (stdout + stderr).strip()
        logger.error("nginx reload failed: %s", err)
        return False, f"Reload failed: {err}"

    def safe_write_and_reload(
        self, domain: str, backend_url: str, ssl_cert: str, ssl_key: str
    ) -> Tuple[bool, str, str]:
        """Write SSL config + reload with automatic rollback on failure."""
        config_path = self.write_ssl_config(domain, backend_url, ssl_cert, ssl_key)
        ok, msg = self.reload()
        if not ok:
            logger.error("Rolling back bad config for %s", domain)
            self.remove_domain_config(domain)
            self.reload()
            return False, "", msg
        return True, config_path, msg

    # ── Status ────────────────────────────────────────────────────────────────

    def list_active_domains(self) -> list[str]:
        enabled = Path(settings.NGINX_SITES_ENABLED)
        if not enabled.exists():
            return []
        return [
            p.name[:-5]
            for p in enabled.iterdir()
            if p.name.endswith(".conf") and not p.name.endswith(".http.conf")
        ]

    def is_nginx_running(self) -> bool:
        rc, _, _ = subprocess.run(
            ["pgrep", "-x", "nginx"], capture_output=True
        ), 0, 0
        return rc[0].returncode == 0
