"""
Nginx configuration manager.

Architecture
------------
/etc/nginx/nginx.conf               <- main config (ships with package, we patch it)
/etc/nginx/snippets/ssl-params.conf <- shared TLS settings (written once)
/etc/nginx/sites-available/<domain>.conf   <- generated per-domain (managed here)
/etc/nginx/sites-enabled/<domain>.conf     <- symlink to sites-available

HTTP-only config (pre-SSL / ACME challenge):
  /etc/nginx/sites-available/<domain>.http.conf

Scalability note
----------------
nginx -s reload is a GRACEFUL reload: worker processes finish in-flight
requests, then are replaced. It is safe to call after every domain change.
For very high frequency changes, batch them (add N domains, then reload once).
"""

import logging
import os
import subprocess
from pathlib import Path
from typing import Tuple

from ..config import settings

logger = logging.getLogger(__name__)

# ── Templates (inline – no extra dependency on Jinja2 for core logic) ─────────

_HTTP_ONLY_CONF = """\
# HTTP-only config for {domain}
# Used for ACME HTTP-01 challenge BEFORE the SSL cert is issued.
server {{
    listen 80;
    server_name {domain};

    # ACME challenge – shared webroot
    location /.well-known/acme-challenge/ {{
        root {acme_webroot};
        try_files $uri =404;
    }}

    # Redirect everything else to HTTPS (even before cert exists,
    # so crawlers see the right headers immediately after DNS change)
    location / {{
        return 301 https://$host$request_uri;
    }}
}}
"""

_SSL_CONF = """\
# HTTPS config for {domain}
# Generated by translation-proxy control plane.
# !! DO NOT EDIT MANUALLY – changes will be overwritten !!

server {{
    listen 80;
    server_name {domain};

    location /.well-known/acme-challenge/ {{
        root {acme_webroot};
        try_files $uri =404;
    }}

    location / {{
        return 301 https://$host$request_uri;
    }}
}}

server {{
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name {domain};

    # ── TLS ──────────────────────────────────────────────────────────────────
    ssl_certificate     {ssl_cert};
    ssl_certificate_key {ssl_key};
    include             {snippets_dir}/ssl-params.conf;

    # ── Security headers ─────────────────────────────────────────────────────
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options SAMEORIGIN always;

    # ── Proxy ─────────────────────────────────────────────────────────────────
    location / {{
        proxy_pass         {backend_url};
        proxy_http_version 1.1;
        proxy_set_header   Upgrade          $http_upgrade;
        proxy_set_header   Connection       "upgrade";
        proxy_set_header   Host             $host;
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;

        # Timeouts
        proxy_connect_timeout 10s;
        proxy_send_timeout    60s;
        proxy_read_timeout    60s;

        # Buffering
        proxy_buffering         on;
        proxy_buffer_size       16k;
        proxy_buffers           8 16k;
        proxy_busy_buffers_size 32k;
    }}
}}
"""

_SSL_PARAMS = """\
# Shared TLS configuration snippet
# Generated by translation-proxy – safe to customise.

ssl_protocols TLSv1.2 TLSv1.3;
ssl_prefer_server_ciphers off;

# Generated with:  openssl dhparam -out /etc/nginx/dhparam.pem 2048
# (created by setup.sh)
ssl_dhparam /etc/nginx/dhparam.pem;

ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:\
ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:\
ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:\
DHE-RSA-AES128-GCM-SHA256;

ssl_session_cache   shared:SSL:10m;
ssl_session_timeout 1d;
ssl_session_tickets off;

ssl_stapling        on;
ssl_stapling_verify on;
resolver 8.8.8.8 1.1.1.1 valid=300s;
resolver_timeout 5s;
"""


# ── Helpers ───────────────────────────────────────────────────────────────────

def _run(cmd: list[str], timeout: int = 30) -> Tuple[int, str, str]:
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
    return result.returncode, result.stdout, result.stderr


def _available_path(domain: str, suffix: str = "") -> Path:
    name = f"{domain}{suffix}.conf"
    return Path(settings.NGINX_SITES_AVAILABLE) / name


def _enabled_path(domain: str, suffix: str = "") -> Path:
    name = f"{domain}{suffix}.conf"
    return Path(settings.NGINX_SITES_ENABLED) / name


def _enable(domain: str, suffix: str = "") -> None:
    avail = _available_path(domain, suffix)
    enbld = _enabled_path(domain, suffix)
    if not enbld.exists():
        enbld.symlink_to(avail)


def _disable(domain: str, suffix: str = "") -> None:
    enbld = _enabled_path(domain, suffix)
    if enbld.exists() or enbld.is_symlink():
        enbld.unlink()


# ── Public API ────────────────────────────────────────────────────────────────

class NginxManager:
    def __init__(self):
        self._ensure_dirs()
        self._write_ssl_params()

    # ── Initialisation ────────────────────────────────────────────────────────

    def _ensure_dirs(self):
        for d in [
            settings.NGINX_SITES_AVAILABLE,
            settings.NGINX_SITES_ENABLED,
            settings.NGINX_SNIPPETS_DIR,
            settings.NGINX_ACME_WEBROOT,
        ]:
            os.makedirs(d, exist_ok=True)

    def _write_ssl_params(self):
        path = Path(settings.NGINX_SNIPPETS_DIR) / "ssl-params.conf"
        if not path.exists():
            path.write_text(_SSL_PARAMS)
            logger.info("Written ssl-params.conf to %s", path)

    # ── HTTP-only (pre-SSL) ───────────────────────────────────────────────────

    def write_http_only_config(self, domain: str) -> str:
        """
        Create an HTTP-only config so the ACME challenge works before
        the SSL cert has been issued. Returns the config file path.
        """
        content = _HTTP_ONLY_CONF.format(
            domain=domain,
            acme_webroot=settings.NGINX_ACME_WEBROOT,
        )
        path = _available_path(domain, ".http")
        path.write_text(content)
        _enable(domain, ".http")
        logger.info("HTTP-only config written for %s", domain)
        return str(path)

    def remove_http_only_config(self, domain: str) -> None:
        _disable(domain, ".http")
        p = _available_path(domain, ".http")
        if p.exists():
            p.unlink()

    # ── Full SSL config ───────────────────────────────────────────────────────

    def write_ssl_config(
        self, domain: str, backend_url: str, ssl_cert: str, ssl_key: str
    ) -> str:
        """
        Write the full HTTPS reverse-proxy config for a domain.
        Returns the config file path.
        """
        content = _SSL_CONF.format(
            domain=domain,
            backend_url=backend_url,
            ssl_cert=ssl_cert,
            ssl_key=ssl_key,
            acme_webroot=settings.NGINX_ACME_WEBROOT,
            snippets_dir=settings.NGINX_SNIPPETS_DIR,
        )
        path = _available_path(domain)
        path.write_text(content)
        _enable(domain)

        # Remove the http-only config once the full one is in place
        self.remove_http_only_config(domain)

        logger.info("SSL config written for %s → %s", domain, backend_url)
        return str(path)

    # ── Remove a domain ───────────────────────────────────────────────────────

    def remove_domain_config(self, domain: str) -> None:
        """Remove both configs (http-only + ssl) for a domain."""
        _disable(domain)
        _disable(domain, ".http")
        for p in [_available_path(domain), _available_path(domain, ".http")]:
            if p.exists():
                p.unlink()
        logger.info("Nginx config removed for %s", domain)

    # ── Validate & reload ─────────────────────────────────────────────────────

    def test_config(self) -> Tuple[bool, str]:
        """Run `nginx -t` to validate configuration."""
        rc, stdout, stderr = _run(["nginx", "-t"])
        ok = rc == 0
        msg = (stdout + stderr).strip()
        if ok:
            logger.info("nginx -t OK")
        else:
            logger.error("nginx -t FAILED: %s", msg)
        return ok, msg

    def reload(self) -> Tuple[bool, str]:
        """
        Gracefully reload nginx.
        Always test config first to avoid crashing the live proxy.
        """
        ok, msg = self.test_config()
        if not ok:
            return False, f"Config test failed – reload aborted: {msg}"
        rc, stdout, stderr = _run(["nginx", "-s", "reload"])
        if rc == 0:
            logger.info("nginx reloaded successfully")
            return True, "nginx reloaded"
        err = (stdout + stderr).strip()
        logger.error("nginx reload failed: %s", err)
        return False, f"Reload failed: {err}"

    def safe_write_and_reload(
        self, domain: str, backend_url: str, ssl_cert: str, ssl_key: str
    ) -> Tuple[bool, str, str]:
        """
        Write SSL config + reload.  On failure, remove the bad config and reload
        the previous good state.  Returns (success, config_path, message).
        """
        config_path = self.write_ssl_config(domain, backend_url, ssl_cert, ssl_key)
        ok, msg = self.reload()
        if not ok:
            logger.error("Roll back: removing bad config for %s", domain)
            self.remove_domain_config(domain)
            self.reload()   # restore previous state
            return False, "", msg
        return True, config_path, msg

    # ── Status ────────────────────────────────────────────────────────────────

    def list_active_domains(self) -> list[str]:
        """Return list of domains that have an enabled nginx config."""
        enabled = Path(settings.NGINX_SITES_ENABLED)
        domains = []
        for p in enabled.iterdir():
            name = p.name
            if name.endswith(".conf") and not name.endswith(".http.conf"):
                domains.append(name[:-5])   # strip .conf
        return domains

    def is_nginx_running(self) -> bool:
        rc, _, _ = _run(["pgrep", "-x", "nginx"])
        return rc == 0
